#!/bin/sh
set -e
. /usr/share/debconf/confmodule
if [ "$1" = "configure" ] && [ ! -z "$2" ] && \
   dpkg --compare-versions "$2" lt 1.0; then
	db_input high isync/upgrade_1.0 || true
	db_go || true
fi
